# Generated by Django 2.1.2 on 2019-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='タイトル')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('created_at', models.DateTimeField(verbose_name='作成日')),
                ('updated_at', models.DateTimeField(verbose_name='更新日')),
            ],
        ),
    ]
