# Generated by Django 2.1.2 on 2019-05-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名前'),
        ),
    ]
