# Generated by Django 2.1.2 on 2019-05-03 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('start_date', models.DateTimeField(verbose_name='開始日')),
                ('end_date', models.DateTimeField(verbose_name='終了日')),
                ('description', models.TextField(verbose_name='予定の内容')),
                ('created_at', models.DateTimeField(verbose_name='作成日')),
                ('updated_at', models.DateTimeField(verbose_name='更新日')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='氏名')),
                ('birthday', models.CharField(max_length=8, verbose_name='生年月日')),
                ('age', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='年齢')),
                ('school_year', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='学年')),
                ('address', models.CharField(default='東京都', max_length=100, verbose_name='住所')),
                ('photo_path', models.CharField(default='0', max_length=100, verbose_name='写真のパス')),
                ('payment', models.IntegerField(default=0, verbose_name='月謝')),
                ('parent_name', models.CharField(max_length=30, verbose_name='保護者氏名')),
                ('parent_email', models.EmailField(default='example@aaa.com', max_length=50, verbose_name='メールアドレス')),
                ('parent_phone', models.CharField(default='00000000000', max_length=11, verbose_name='電話番号')),
                ('created_at', models.DateTimeField(verbose_name='作成日')),
                ('updated_at', models.DateTimeField(verbose_name='更新日')),
            ],
        ),
    ]
