# Generated by Django 2.1.2 on 2019-04-27 08:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=30, unique=True)),
                ('parent_email', models.EmailField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='create datetime')),
                ('updated_at', models.DateTimeField(verbose_name='update datetime')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_birthday', models.CharField(max_length=8)),
                ('student_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('created_at', models.DateTimeField(verbose_name='create datetime')),
                ('updated_at', models.DateTimeField(verbose_name='update datetime')),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Parents', to_field='parent_name')),
            ],
        ),
    ]
