# Generated by Django 2.1.2 on 2019-04-29 06:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_school_year',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='学年'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='created_at',
            field=models.DateTimeField(verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='parent_email',
            field=models.EmailField(max_length=50, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='parent_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='parents',
            name='updated_at',
            field=models.DateTimeField(verbose_name='更新日'),
        ),
        migrations.AlterField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Parents', to_field='parent_name', verbose_name='保護者氏名'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_birthday',
            field=models.CharField(max_length=8, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_name',
            field=models.CharField(max_length=30, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(verbose_name='更新日'),
        ),
    ]
